theme: jekyll-theme-tactile
title: Maksim Anisimov's personal webpage
description: Hi, my name is Max, I am a data scientist / quant currently working at causaLens in London. I am using this website to reflect on, dig deep into and share things I have learned. I hope this website will help you understand world better and raise interest in fields I am passionate about.
